# AI Provider Configuration
ai:
  providers:
    ollama:
      baseUrl: "http://localhost:11434"
      models:
        - "gpt-oss"
      defaultModel: "gpt-oss"

    openai:
      baseUrl: "https://api.openai.com/v1"
      models:
        - "gpt-5-2025-08-07"
        - "gpt-5-mini"
        - "gpt-5-nano"
      defaultModel: "gpt-5-mini-2025-08-07"

    anthropic:
      baseUrl: "https://api.anthropic.com"
      models:
        - "claude-opus-4-1-20250805"
        - "claude-sonnet-4-20250514"
        - "claude-3-5-haiku-20241022"
      defaultModel: "claude-3-5-haiku-20241022"
      apiVersion: "2023-06-01"
      maxTokens: 8192

# Multi-Agent Research System Configuration
research:
  enabled: true
  orchestrator:
    maxTokens: 4000
    temperature: 0.1
    enableThinking: true

  agents:
    BookSearchAgent:
      enabled: true
      maxResults: 5
    EvidenceAgent:
      enabled: true
      evidenceTypes: ["examples", "statistics", "quotes", "case_studies"]
    AnalysisAgent:
      enabled: true
      maxCrossReferences: 10
    ContextAgent:
      enabled: true
      includeStructure: true

# Application Settings
app:
  name: "AI Document Reader"
  version: "2.1.0"
  features:
    multiAgentResearch: true
    fullBookContext: true
    persistentConversations: true
    libraryManagement: true
